openapi: 3.0.0
info:
  title: Swagger Airports API
  version: v1
  description: A test project to generate API docs
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
  contact:
    name: Multiverse
    url: 'https://www.multiverse.io'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jeffery.forbes/MvAirport/v1
  - url: 'http://localhost:3000'
paths:

  /airports:
    get:
      summary: returns an array of airports
      tags:
        - Airports
      responses:
        '200':
          description: returns an array of airports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
                  
  /createAirport:
    post:
      summary: creates a new airport into the collection.
      tags:
        - Airports
      responses:
        '200':
          description: Successs - Created a new airport
                  
                  
  /airport/{icao}:
    get:
      summary: returns an specific airport based on the icao.
      parameters:
        - in: path
          name: icao
          schema: 
            type: string
          required: true
          description: String icao that is unique to the airport
      tags:
        - Airports
      responses:
        '200':
          description: the airport matching the `icao`
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Airport'
                  
                  
  /updateAirport/{icao}:
    put:
      summary: updates a existing airport into the collection
      parameters: 
      - in: path
        name: icao
        schema:
          type: string
        required: true
      tags:
        - Airports
      responses:
        '200':
          description: Success - Updated `icao` in the collection
          
                  
  /deleteAirport/{icao}:
    delete:
      summary: deletes a existing airport from the collection
      parameters: 
      - in: path
        name: icao
        schema:
          type: string
        required: true
      tags:
        - Airports
      responses:
        '200':
          description: Successs - Airport deleted
        
        
components:
  schemas:
    Airport:
      type: object
      properties:
        icao:
          type: string
        iata:
          type: string
        name:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        elevation:
          type: integer
        lat:
          type: number
        lon:
          type: number
        tz:
          type: string
      example:
        icao: 00AK
        iata: ''
        name: Lowell Field
        city: Anchor Point
        state: Alaska
        country: US
        elevation: 450
        lat: 59.94919968
        lon: -151.695999146
        tz: America/Anchorage
tags:
  - name: Airports
    description: Airport management